# Generated by Django 2.2.5 on 2019-09-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='funder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funder.Funder'),
            preserve_default=False,
        ),
    ]
