# Generated by Django 2.2.5 on 2019-09-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funder', '0003_auto_20190920_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
