# Generated by Django 2.2.5 on 2019-09-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='remained_fee',
            field=models.IntegerField(blank=True),
        ),
    ]
