# Generated by Django 2.2.5 on 2019-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190920_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fee_count',
            field=models.IntegerField(default=0),
        ),
    ]
